Dev modal window
PriTexX/polytech-discordbot pull request #3
Opened 2023-03-04 08:15 UTC by DmitriiDerendyaev

on_join_member, modalWindow

2023-03-04 09:43 UTC, PriTexX commented on requirements.txt
> +disnake~=2.8.0
ненужная зависимость

2023-03-04 09:56 UTC, PriTexX requested changes

2023-03-04 09:56 UTC, PriTexX commented on UI/discordModal.py
> +class my_modal(ui.Modal, title="Greeting window"):
Классы так не называют. Корректное название в данном случае будет - MyModal, но оно не отражает сути того, что из себя представляет сам класс, лучше назвать его более осмысленно, например LoginModal

2023-03-04 09:56 UTC, PriTexX commented on bot/cogs/ExampleCog.py
> +from UI.discordModal import my_modal
так лучше не делать, UI нужно переименовать в ui и перенести в папку bot, также из него нужно сделать пакет, для этого там нужно добавить файл __init__.py. Пример можешь глянуть в пакете services

2023-03-04 09:56 UTC, PriTexX commented on bot/cogs/ExampleCog.py
> +    bot = commands.Bot(command_prefix="!")
Это вообще работать не должно. Ты инициализируешь какой-то новый полу-инстанс клиента, хотя он уже есть и даже не запускаешь его. В строках 13-15 есть пример, как правильно навесить обработчик события, не нужно было ничего придумывать.

2023-03-04 09:56 UTC, PriTexX commented on bot/cogs/ExampleCog.py
> +    async def on_member_join(member):
Этот класс ExampleCog нужен только для примера, чтобы показать всем, как создавать команды и обработчики событий, если хочешь навесить обработчик на on_member_join, то создай другой класс(и назови его EventHandlersCog) и повтори логику из этого.

2023-03-06 07:58 UTC, DmitriiDerendyaev commented on UI/discordModal.py
> +class my_modal(ui.Modal, title="Greeting window"):
Класс и все его упоминания заменены на LoginModal

2023-03-06 07:58 UTC, DmitriiDerendyaev commented on requirements.txt
> +disnake~=2.8.0
Зависимость убрал

2023-03-06 07:58 UTC, DmitriiDerendyaev commented on bot/cogs/ExampleCog.py
> +from UI.discordModal import my_modal
__init__.py добавлен, импортирован класс

2023-03-06 07:58 UTC, DmitriiDerendyaev commented on bot/cogs/ExampleCog.py
> +    bot = commands.Bot(command_prefix="!")
Объявление команды убрано, логика вынесена в отдельный класс

2023-03-06 07:58 UTC, DmitriiDerendyaev commented on bot/cogs/ExampleCog.py
> +    async def on_member_join(member):
Логика вынесена в отдельный класс

2023-03-06 08:02 UTC, merged